import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/app-icon.svg" }],
    apple: [{ url: "/app-icon.svg" }],
  },
};
